import { logger } from "../logger";
import type { ChannelResult } from "./types";

export type { ChannelResult };

export interface EmailMessage {
  to: string;
  subject: string;
  body: string;
  department: string;
  priority: string;
  sla: string;
  requestId: number;
  fromName?: string;
}

function generateMessageId(): string {
  const rand = Math.random().toString(36).substring(2, 18);
  return `<lumetra-${rand}@lumetra.ai>`;
}

function buildSubject(msg: EmailMessage): string {
  const flag =
    msg.priority === "CRITICAL"
      ? "[CRITICAL] "
      : msg.priority === "HIGH"
        ? "[HIGH] "
        : "";
  return `${flag}${msg.department} — Lumetra Ref LMT-${msg.requestId}`;
}

function buildPlainText(msg: EmailMessage): string {
  const divider = "─".repeat(60);
  return [
    `${msg.fromName ? `Dear ${msg.fromName},\n\n` : ""}${msg.body}`,
    "",
    divider,
    `Department : ${msg.department}`,
    `Priority   : ${msg.priority}`,
    `SLA        : ${msg.sla}`,
    `Reference  : LMT-${msg.requestId}`,
    divider,
    "This message was generated by the Lumetra deterministic intake engine.",
    "Do not reply to this address. For urgent matters please call our helpline.",
  ].join("\n");
}

export async function sendEmail(msg: EmailMessage): Promise<ChannelResult> {
  const timestamp = new Date().toISOString();

  if (!msg.to || msg.to.trim() === "") {
    return { channel: "email", status: "no_contact", timestamp };
  }

  const apiKey = process.env.SENDGRID_API_KEY;
  const fromAddress =
    process.env.SENDGRID_FROM_ADDRESS ?? "noreply@lumetra.ai";

  if (!apiKey) {
    logger.info(
      {
        channel: "email",
        to: msg.to,
        priority: msg.priority,
        dept: msg.department,
      },
      "[STUB] Email dispatch simulated — set SENDGRID_API_KEY to enable live sending",
    );
    return {
      channel: "email",
      status: "sent",
      messageId: generateMessageId(),
      to: msg.to,
      timestamp,
    };
  }

  try {
    const priorityHeader =
      msg.priority === "CRITICAL" || msg.priority === "HIGH"
        ? "1 (Highest)"
        : "3 (Normal)";

    const payload = {
      personalizations: [{ to: [{ email: msg.to }] }],
      from: { email: fromAddress, name: "Lumetra Intake" },
      subject: buildSubject(msg),
      content: [{ type: "text/plain", value: buildPlainText(msg) }],
      headers: {
        "X-Priority": priorityHeader,
        "X-Lumetra-Department": msg.department,
        "X-Lumetra-Ref": `LMT-${msg.requestId}`,
      },
    };

    const res = await fetch("https://api.sendgrid.com/v3/mail/send", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const body = await res.text();
      logger.error(
        { channel: "email", httpStatus: res.status, body },
        "SendGrid send failed",
      );
      return {
        channel: "email",
        status: "failed",
        timestamp,
        error: `HTTP ${res.status}`,
      };
    }

    const msgId = res.headers.get("X-Message-Id") ?? generateMessageId();
    return {
      channel: "email",
      status: "sent",
      messageId: msgId,
      to: msg.to,
      timestamp,
    };
  } catch (err) {
    logger.error({ err }, "Email send threw");
    return {
      channel: "email",
      status: "failed",
      timestamp,
      error: String(err),
    };
  }
}
